#!/bin/bash

echo "Have you copied the btleplug & jini-utils-rs repo into the android-files?"
echo "begin copy..."

# make dirs
mkdir -p android/app/src/main/java/io/bitshift/bike_aid/
mkdir -p android/gradle/wrapper/

# gradle files
cp android-files/build.gradle android/
cp android-files/gradle.properties android/
cp android-files/build.gradle android/
cp android-files/settings.gradle android/
cp android-files/proguard-rules.pro android/
cp android-files/gradlew android/
cp android-files/gradlew.bat android/

# gradle wrapper
cp android-files/gradle-wrapper.properties android/gradle/wrapper/
cp android-files/gradle-wrapper.jar android/gradle/wrapper/

# plugins/libs
cp -f -r android-files/jni-utils-rs/java/src/main/java/io android/app/src/main/java/
cp -f -r android-files/btleplug/src/droidplug/java/src/main/java/com android/app/src/main/java/

# manifest
cp android-files/AndroidManifest.xml android/app/src/main/

# source
#cp android-files/MainActivity.java android/app/src/main/java/io/bitshift/bike_aid

# key
#cp android-files/key.properties android/
#KEY=android/key.properties
#echo >> $KEY
#echo password=${ANDROID_SIGN_PASSWORD} >> $KEY

echo "complete!"
echo "From the android dir, make a build using:"
echo "./gradlew tasks"
echo "./gradlew assembleDebug"
