[package]
edition = "2021"
name = "bike-aid-nrf-rs"
version = "0.1.0"
authors = ["bronsonmathews@gmail.com"]

[dependencies]
embassy-futures = { version = "0.1.0"}
embassy-sync = { version = "0.6.0", features = ["defmt"] }
embassy-executor = { version = "0.5.0", features = ["task-arena-size-32768", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-time = { version = "0.3.1", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-nrf = { version = "0.1.0", features = ["defmt", "nrf52840", "time-driver-rtc1", "gpiote", "unstable-pac", "time"] }

# log
defmt = "0.3"
defmt-rtt = "0.4"

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"

static_cell = { version = "2" }
panic-probe = { version = "0.3", features = ["print-defmt"] }
serde = { version = "1.0.136", default-features = false }

# device driver
mcp4725 = "0.4.2"

# maths
num-traits = { version = "0.2.19", default-features = false, features = ["libm"] }

[profile.release]
debug = 2
