// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/protocol.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1300515756;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_bike_aid',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Uint8List crateApiProtocolCreateCommandBytes({
    required ScooterCommand command,
    required ScooterState currentState,
  });

  BleAction crateApiProtocolGetCommandAction({
    required ScooterCommand command,
    required ScooterState currentState,
  });

  String crateApiProtocolGetTargetDeviceName();

  ParseResult crateApiProtocolParseCharacteristicData({
    required ScooterState state,
    required String uuid,
    required List<int> data,
  });

  Future<ScooterState> crateApiProtocolScooterStateDefault();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Uint8List crateApiProtocolCreateCommandBytes({
    required ScooterCommand command,
    required ScooterState currentState,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_scooter_command(command, serializer);
          sse_encode_box_autoadd_scooter_state(currentState, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolCreateCommandBytesConstMeta,
        argValues: [command, currentState],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolCreateCommandBytesConstMeta =>
      const TaskConstMeta(
        debugName: "create_command_bytes",
        argNames: ["command", "currentState"],
      );

  @override
  BleAction crateApiProtocolGetCommandAction({
    required ScooterCommand command,
    required ScooterState currentState,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_scooter_command(command, serializer);
          sse_encode_box_autoadd_scooter_state(currentState, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ble_action,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolGetCommandActionConstMeta,
        argValues: [command, currentState],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolGetCommandActionConstMeta =>
      const TaskConstMeta(
        debugName: "get_command_action",
        argNames: ["command", "currentState"],
      );

  @override
  String crateApiProtocolGetTargetDeviceName() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolGetTargetDeviceNameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolGetTargetDeviceNameConstMeta =>
      const TaskConstMeta(debugName: "get_target_device_name", argNames: []);

  @override
  ParseResult crateApiProtocolParseCharacteristicData({
    required ScooterState state,
    required String uuid,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_scooter_state(state, serializer);
          sse_encode_String(uuid, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_parse_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolParseCharacteristicDataConstMeta,
        argValues: [state, uuid, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolParseCharacteristicDataConstMeta =>
      const TaskConstMeta(
        debugName: "parse_characteristic_data",
        argNames: ["state", "uuid", "data"],
      );

  @override
  Future<ScooterState> crateApiProtocolScooterStateDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_scooter_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolScooterStateDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolScooterStateDefaultConstMeta =>
      const TaskConstMeta(debugName: "scooter_state_default", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BleAction dco_decode_ble_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BleAction(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      serviceUuid: dco_decode_String(arr[1]),
      characteristicUuid: dco_decode_String(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ScooterCommand dco_decode_box_autoadd_scooter_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_scooter_command(raw);
  }

  @protected
  ScooterState dco_decode_box_autoadd_scooter_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_scooter_state(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ParseResult dco_decode_parse_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ParseResult(
      state: dco_decode_scooter_state(arr[0]),
      log: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  ScooterCommand dco_decode_scooter_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ScooterCommand_TogglePower();
      case 1:
        return ScooterCommand_ToggleAlarm();
      case 2:
        return ScooterCommand_ToggleSport();
      case 3:
        return ScooterCommand_ToggleLights();
      case 4:
        return ScooterCommand_CruiseUp();
      case 5:
        return ScooterCommand_CruiseDown();
      case 6:
        return ScooterCommand_Horn();
      case 7:
        return ScooterCommand_SetUart(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ScooterState dco_decode_scooter_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 16)
      throw Exception('unexpected arr length: expect 16 but see ${arr.length}');
    return ScooterState(
      powerOn: dco_decode_bool(arr[0]),
      alarmOn: dco_decode_bool(arr[1]),
      sportOn: dco_decode_bool(arr[2]),
      lightsOn: dco_decode_bool(arr[3]),
      hornActive: dco_decode_bool(arr[4]),
      speed: dco_decode_String(arr[5]),
      throttleLevel: dco_decode_String(arr[6]),
      temperature: dco_decode_String(arr[7]),
      clockMinutes: dco_decode_String(arr[8]),
      clockHours: dco_decode_String(arr[9]),
      cruiseLevel: dco_decode_i_32(arr[10]),
      batteryLevel: dco_decode_String(arr[11]),
      batteryPower: dco_decode_String(arr[12]),
      brakeActive: dco_decode_bool(arr[13]),
      parkBrakeActive: dco_decode_bool(arr[14]),
      odometer: dco_decode_String(arr[15]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BleAction sse_decode_ble_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_serviceUuid = sse_decode_String(deserializer);
    var var_characteristicUuid = sse_decode_String(deserializer);
    return BleAction(
      bytes: var_bytes,
      serviceUuid: var_serviceUuid,
      characteristicUuid: var_characteristicUuid,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ScooterCommand sse_decode_box_autoadd_scooter_command(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_scooter_command(deserializer));
  }

  @protected
  ScooterState sse_decode_box_autoadd_scooter_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_scooter_state(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ParseResult sse_decode_parse_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_scooter_state(deserializer);
    var var_log = sse_decode_opt_String(deserializer);
    return ParseResult(state: var_state, log: var_log);
  }

  @protected
  ScooterCommand sse_decode_scooter_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ScooterCommand_TogglePower();
      case 1:
        return ScooterCommand_ToggleAlarm();
      case 2:
        return ScooterCommand_ToggleSport();
      case 3:
        return ScooterCommand_ToggleLights();
      case 4:
        return ScooterCommand_CruiseUp();
      case 5:
        return ScooterCommand_CruiseDown();
      case 6:
        return ScooterCommand_Horn();
      case 7:
        var var_field0 = sse_decode_String(deserializer);
        return ScooterCommand_SetUart(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ScooterState sse_decode_scooter_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_powerOn = sse_decode_bool(deserializer);
    var var_alarmOn = sse_decode_bool(deserializer);
    var var_sportOn = sse_decode_bool(deserializer);
    var var_lightsOn = sse_decode_bool(deserializer);
    var var_hornActive = sse_decode_bool(deserializer);
    var var_speed = sse_decode_String(deserializer);
    var var_throttleLevel = sse_decode_String(deserializer);
    var var_temperature = sse_decode_String(deserializer);
    var var_clockMinutes = sse_decode_String(deserializer);
    var var_clockHours = sse_decode_String(deserializer);
    var var_cruiseLevel = sse_decode_i_32(deserializer);
    var var_batteryLevel = sse_decode_String(deserializer);
    var var_batteryPower = sse_decode_String(deserializer);
    var var_brakeActive = sse_decode_bool(deserializer);
    var var_parkBrakeActive = sse_decode_bool(deserializer);
    var var_odometer = sse_decode_String(deserializer);
    return ScooterState(
      powerOn: var_powerOn,
      alarmOn: var_alarmOn,
      sportOn: var_sportOn,
      lightsOn: var_lightsOn,
      hornActive: var_hornActive,
      speed: var_speed,
      throttleLevel: var_throttleLevel,
      temperature: var_temperature,
      clockMinutes: var_clockMinutes,
      clockHours: var_clockHours,
      cruiseLevel: var_cruiseLevel,
      batteryLevel: var_batteryLevel,
      batteryPower: var_batteryPower,
      brakeActive: var_brakeActive,
      parkBrakeActive: var_parkBrakeActive,
      odometer: var_odometer,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_ble_action(BleAction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_String(self.serviceUuid, serializer);
    sse_encode_String(self.characteristicUuid, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_scooter_command(
    ScooterCommand self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_scooter_command(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_scooter_state(
    ScooterState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_scooter_state(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_parse_result(ParseResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_scooter_state(self.state, serializer);
    sse_encode_opt_String(self.log, serializer);
  }

  @protected
  void sse_encode_scooter_command(
    ScooterCommand self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ScooterCommand_TogglePower():
        sse_encode_i_32(0, serializer);
      case ScooterCommand_ToggleAlarm():
        sse_encode_i_32(1, serializer);
      case ScooterCommand_ToggleSport():
        sse_encode_i_32(2, serializer);
      case ScooterCommand_ToggleLights():
        sse_encode_i_32(3, serializer);
      case ScooterCommand_CruiseUp():
        sse_encode_i_32(4, serializer);
      case ScooterCommand_CruiseDown():
        sse_encode_i_32(5, serializer);
      case ScooterCommand_Horn():
        sse_encode_i_32(6, serializer);
      case ScooterCommand_SetUart(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_scooter_state(ScooterState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.powerOn, serializer);
    sse_encode_bool(self.alarmOn, serializer);
    sse_encode_bool(self.sportOn, serializer);
    sse_encode_bool(self.lightsOn, serializer);
    sse_encode_bool(self.hornActive, serializer);
    sse_encode_String(self.speed, serializer);
    sse_encode_String(self.throttleLevel, serializer);
    sse_encode_String(self.temperature, serializer);
    sse_encode_String(self.clockMinutes, serializer);
    sse_encode_String(self.clockHours, serializer);
    sse_encode_i_32(self.cruiseLevel, serializer);
    sse_encode_String(self.batteryLevel, serializer);
    sse_encode_String(self.batteryPower, serializer);
    sse_encode_bool(self.brakeActive, serializer);
    sse_encode_bool(self.parkBrakeActive, serializer);
    sse_encode_String(self.odometer, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
