// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1300515756;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__protocol__create_command_bytes_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_command_bytes",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_command = <crate::api::protocol::ScooterCommand>::sse_decode(&mut deserializer);
            let api_current_state =
                <crate::api::protocol::ScooterState>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::protocol::create_command_bytes(
                    api_command,
                    api_current_state,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__protocol__get_command_action_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_command_action",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_command = <crate::api::protocol::ScooterCommand>::sse_decode(&mut deserializer);
            let api_current_state =
                <crate::api::protocol::ScooterState>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::protocol::get_command_action(
                    api_command,
                    api_current_state,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__protocol__get_target_device_name_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_target_device_name",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::protocol::get_target_device_name())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__protocol__parse_characteristic_data_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "parse_characteristic_data",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_state = <crate::api::protocol::ScooterState>::sse_decode(&mut deserializer);
            let api_uuid = <String>::sse_decode(&mut deserializer);
            let api_data = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(
                    crate::api::protocol::parse_characteristic_data(api_state, api_uuid, api_data),
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__protocol__scooter_state_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "scooter_state_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::protocol::ScooterState::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::protocol::BleAction {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_bytes = <Vec<u8>>::sse_decode(deserializer);
        let mut var_serviceUuid = <String>::sse_decode(deserializer);
        let mut var_characteristicUuid = <String>::sse_decode(deserializer);
        return crate::api::protocol::BleAction {
            bytes: var_bytes,
            service_uuid: var_serviceUuid,
            characteristic_uuid: var_characteristicUuid,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::protocol::ParseResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_state = <crate::api::protocol::ScooterState>::sse_decode(deserializer);
        let mut var_log = <Option<String>>::sse_decode(deserializer);
        return crate::api::protocol::ParseResult {
            state: var_state,
            log: var_log,
        };
    }
}

impl SseDecode for crate::api::protocol::ScooterCommand {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::protocol::ScooterCommand::TogglePower;
            }
            1 => {
                return crate::api::protocol::ScooterCommand::ToggleAlarm;
            }
            2 => {
                return crate::api::protocol::ScooterCommand::ToggleSport;
            }
            3 => {
                return crate::api::protocol::ScooterCommand::ToggleLights;
            }
            4 => {
                return crate::api::protocol::ScooterCommand::CruiseUp;
            }
            5 => {
                return crate::api::protocol::ScooterCommand::CruiseDown;
            }
            6 => {
                return crate::api::protocol::ScooterCommand::Horn;
            }
            7 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::protocol::ScooterCommand::SetUart(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::protocol::ScooterState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_powerOn = <bool>::sse_decode(deserializer);
        let mut var_alarmOn = <bool>::sse_decode(deserializer);
        let mut var_sportOn = <bool>::sse_decode(deserializer);
        let mut var_lightsOn = <bool>::sse_decode(deserializer);
        let mut var_hornActive = <bool>::sse_decode(deserializer);
        let mut var_speed = <String>::sse_decode(deserializer);
        let mut var_throttleLevel = <String>::sse_decode(deserializer);
        let mut var_temperature = <String>::sse_decode(deserializer);
        let mut var_clockMinutes = <String>::sse_decode(deserializer);
        let mut var_clockHours = <String>::sse_decode(deserializer);
        let mut var_cruiseLevel = <i32>::sse_decode(deserializer);
        let mut var_batteryLevel = <String>::sse_decode(deserializer);
        let mut var_batteryPower = <String>::sse_decode(deserializer);
        let mut var_brakeActive = <bool>::sse_decode(deserializer);
        let mut var_parkBrakeActive = <bool>::sse_decode(deserializer);
        let mut var_odometer = <String>::sse_decode(deserializer);
        return crate::api::protocol::ScooterState {
            power_on: var_powerOn,
            alarm_on: var_alarmOn,
            sport_on: var_sportOn,
            lights_on: var_lightsOn,
            horn_active: var_hornActive,
            speed: var_speed,
            throttle_level: var_throttleLevel,
            temperature: var_temperature,
            clock_minutes: var_clockMinutes,
            clock_hours: var_clockHours,
            cruise_level: var_cruiseLevel,
            battery_level: var_batteryLevel,
            battery_power: var_batteryPower,
            brake_active: var_brakeActive,
            park_brake_active: var_parkBrakeActive,
            odometer: var_odometer,
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        5 => wire__crate__api__protocol__scooter_state_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__protocol__create_command_bytes_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__protocol__get_command_action_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__protocol__get_target_device_name_impl(ptr, rust_vec_len, data_len),
        4 => {
            wire__crate__api__protocol__parse_characteristic_data_impl(ptr, rust_vec_len, data_len)
        }
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::protocol::BleAction {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.bytes.into_into_dart().into_dart(),
            self.service_uuid.into_into_dart().into_dart(),
            self.characteristic_uuid.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::protocol::BleAction
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::protocol::BleAction>
    for crate::api::protocol::BleAction
{
    fn into_into_dart(self) -> crate::api::protocol::BleAction {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::protocol::ParseResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.state.into_into_dart().into_dart(),
            self.log.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::protocol::ParseResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::protocol::ParseResult>
    for crate::api::protocol::ParseResult
{
    fn into_into_dart(self) -> crate::api::protocol::ParseResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::protocol::ScooterCommand {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::protocol::ScooterCommand::TogglePower => [0.into_dart()].into_dart(),
            crate::api::protocol::ScooterCommand::ToggleAlarm => [1.into_dart()].into_dart(),
            crate::api::protocol::ScooterCommand::ToggleSport => [2.into_dart()].into_dart(),
            crate::api::protocol::ScooterCommand::ToggleLights => [3.into_dart()].into_dart(),
            crate::api::protocol::ScooterCommand::CruiseUp => [4.into_dart()].into_dart(),
            crate::api::protocol::ScooterCommand::CruiseDown => [5.into_dart()].into_dart(),
            crate::api::protocol::ScooterCommand::Horn => [6.into_dart()].into_dart(),
            crate::api::protocol::ScooterCommand::SetUart(field0) => {
                [7.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::protocol::ScooterCommand
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::protocol::ScooterCommand>
    for crate::api::protocol::ScooterCommand
{
    fn into_into_dart(self) -> crate::api::protocol::ScooterCommand {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::protocol::ScooterState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.power_on.into_into_dart().into_dart(),
            self.alarm_on.into_into_dart().into_dart(),
            self.sport_on.into_into_dart().into_dart(),
            self.lights_on.into_into_dart().into_dart(),
            self.horn_active.into_into_dart().into_dart(),
            self.speed.into_into_dart().into_dart(),
            self.throttle_level.into_into_dart().into_dart(),
            self.temperature.into_into_dart().into_dart(),
            self.clock_minutes.into_into_dart().into_dart(),
            self.clock_hours.into_into_dart().into_dart(),
            self.cruise_level.into_into_dart().into_dart(),
            self.battery_level.into_into_dart().into_dart(),
            self.battery_power.into_into_dart().into_dart(),
            self.brake_active.into_into_dart().into_dart(),
            self.park_brake_active.into_into_dart().into_dart(),
            self.odometer.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::protocol::ScooterState
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::protocol::ScooterState>
    for crate::api::protocol::ScooterState
{
    fn into_into_dart(self) -> crate::api::protocol::ScooterState {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::protocol::BleAction {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.bytes, serializer);
        <String>::sse_encode(self.service_uuid, serializer);
        <String>::sse_encode(self.characteristic_uuid, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::protocol::ParseResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::protocol::ScooterState>::sse_encode(self.state, serializer);
        <Option<String>>::sse_encode(self.log, serializer);
    }
}

impl SseEncode for crate::api::protocol::ScooterCommand {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::protocol::ScooterCommand::TogglePower => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::protocol::ScooterCommand::ToggleAlarm => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::protocol::ScooterCommand::ToggleSport => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::protocol::ScooterCommand::ToggleLights => {
                <i32>::sse_encode(3, serializer);
            }
            crate::api::protocol::ScooterCommand::CruiseUp => {
                <i32>::sse_encode(4, serializer);
            }
            crate::api::protocol::ScooterCommand::CruiseDown => {
                <i32>::sse_encode(5, serializer);
            }
            crate::api::protocol::ScooterCommand::Horn => {
                <i32>::sse_encode(6, serializer);
            }
            crate::api::protocol::ScooterCommand::SetUart(field0) => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::protocol::ScooterState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.power_on, serializer);
        <bool>::sse_encode(self.alarm_on, serializer);
        <bool>::sse_encode(self.sport_on, serializer);
        <bool>::sse_encode(self.lights_on, serializer);
        <bool>::sse_encode(self.horn_active, serializer);
        <String>::sse_encode(self.speed, serializer);
        <String>::sse_encode(self.throttle_level, serializer);
        <String>::sse_encode(self.temperature, serializer);
        <String>::sse_encode(self.clock_minutes, serializer);
        <String>::sse_encode(self.clock_hours, serializer);
        <i32>::sse_encode(self.cruise_level, serializer);
        <String>::sse_encode(self.battery_level, serializer);
        <String>::sse_encode(self.battery_power, serializer);
        <bool>::sse_encode(self.brake_active, serializer);
        <bool>::sse_encode(self.park_brake_active, serializer);
        <String>::sse_encode(self.odometer, serializer);
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
